steps:
# 1. Build the Docker image for the frontend
# VITE_API_URL and VITE_GEMINI_API_KEY are needed at build time (baked into bundle)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Frontend Image'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build \
        --no-cache \
        --build-arg VITE_API_URL=https://backend-phd2mjs6qa-uc.a.run.app/api \
        --build-arg VITE_GEMINI_API_KEY=$$GEMINI_KEY \
        -t gcr.io/$PROJECT_ID/frontend:latest \
        -t gcr.io/$PROJECT_ID/frontend:$BUILD_ID \
        .
  secretEnv: ['GEMINI_KEY']

# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Frontend Image'
  args:
    - 'push'
    - '--all-tags'
    - 'gcr.io/$PROJECT_ID/frontend'

# 2. Deploy the built image to Cloud Run
# Note: VITE_GEMINI_API_KEY is now baked into the bundle at build time
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'frontend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/frontend:latest'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--memory'
    - '256Mi'
    - '--timeout'
    - '300'
    - '--update-env-vars'
    - 'VITE_API_URL=https://backend-phd2mjs6qa-uc.a.run.app/api'

# 3. Define where the secrets come from (for build step)
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/VITE_GEMINI_API_KEY_SECRET/versions/latest
      env: 'GEMINI_KEY'