
import React, { useState, useMemo } from 'react';
import { Strategy, Benchmark } from '../types';
import { CloseIcon } from './icons/Icons';

interface DefaultDataExporterProps {
    strategies: Strategy[];
    benchmarks: Benchmark[];
}

const DefaultDataExporter: React.FC<DefaultDataExporterProps> = ({ strategies, benchmarks }) => {
    const [showModal, setShowModal] = useState(false);

    const generatedFileContent = useMemo(() => {
        const strategiesJSON = JSON.stringify(strategies, null, 2);
        const benchmarksJSON = JSON.stringify(benchmarks, null, 2);

        return `import { Strategy, Benchmark } from '../types';

// This file was automatically generated by the "Set as Default" feature in the admin panel.
// To update the default strategies and benchmarks, use the admin panel to generate new content for this file.

export const initialStrategies: Strategy[] = ${strategiesJSON};

export const initialBenchmarks: Benchmark[] = ${benchmarksJSON};
`;
    }, [strategies, benchmarks]);

    return (
        <>
            <button
                onClick={() => setShowModal(true)}
                className="bg-blue-600 text-white font-semibold py-2 px-4 rounded-lg hover:bg-blue-700 w-full md:w-auto"
            >
                Generate New Default Data File
            </button>

            {showModal && (
                <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex justify-center items-center p-4" onClick={() => setShowModal(false)}>
                    <div className="bg-white rounded-lg shadow-xl p-8 w-full max-w-2xl" onClick={e => e.stopPropagation()}>
                        <div className="flex justify-between items-center mb-4">
                            <h2 className="text-2xl font-bold text-gray-800">New mockData.ts Content</h2>
                            <button onClick={() => setShowModal(false)} className="text-gray-400 hover:text-gray-600">
                                <CloseIcon />
                            </button>
                        </div>
                        <p className="text-sm text-gray-600 mb-4">Copy the code below and replace the entire content of the <code className="bg-gray-200 text-red-600 px-1 rounded">data/mockData.ts</code> file.</p>
                        <textarea
                            readOnly
                            value={generatedFileContent}
                            className="w-full h-64 p-2 border border-gray-300 rounded-md font-mono text-xs bg-gray-50"
                            onClick={(e) => (e.target as HTMLTextAreaElement).select()}
                        />
                        <div className="flex justify-end space-x-4 mt-6">
                            <button
                                onClick={() => {
                                    navigator.clipboard.writeText(generatedFileContent);
                                    alert('Code Copied to clipboard!');
                                }}
                                className="py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700"
                            >
                                Copy Code
                            </button>
                            <button
                                onClick={() => setShowModal(false)}
                                className="py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50"
                            >
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </>
    );
};

export default DefaultDataExporter;
